# Generated by Django 3.0.4 on 2020-05-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='end_skills',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='start_skills',
        ),
    ]
