# Generated by Django 3.0.4 on 2020-06-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_auto_20200504_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='units',
        ),
    ]
