# Generated by Django 3.0.4 on 2020-06-14 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0005_remove_curriculum_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='prerequisite_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
