# Generated by Django 3.0.4 on 2020-03-20 06:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MC', 'Multiple Choice'), ('NI', 'Numerical Input'), ('FI', 'Function Input'), ('MI', 'Matrix Input'), ('II', 'Interval Input')], max_length=2)),
                ('question_prompt', models.TextField()),
                ('is_mastery', models.BooleanField(default=False)),
                ('discrimination', models.DecimalField(decimal_places=3, default=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('pseudochance', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('prompt_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Image')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skills.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_explanation', models.TextField(blank=True, null=True)),
                ('answer_correctness', models.DecimalField(decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('answer_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question')),
            ],
        ),
    ]
