# Generated by Django 3.0.4 on 2020-03-24 03:58

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.answer_image_directory_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt_image',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.prompt_image_directory_path),
        ),
    ]
