# Generated by Django 3.0.4 on 2020-03-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200323_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
