# Generated by Django 3.0.4 on 2020-03-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('IC', 'Image Choice'), ('NI', 'Numerical Input'), ('FI', 'Function Input'), ('MI', 'Matrix Input'), ('II', 'Interval Input')], max_length=2),
        ),
    ]
