# Generated by Django 3.0.4 on 2020-06-04 01:30

import django.contrib.postgres.fields
from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200328_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='permitted_symbols',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=questions.models.get_default_permitted_fields, null=True, size=None),
        ),
    ]
