# Generated by Django 3.0.4 on 2020-05-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20200426_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='end_skills',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='start_skills',
        ),
    ]
