# Generated by Django 3.0.4 on 2020-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20200504_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='topological_average',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
