# Generated by Django 3.0.4 on 2020-05-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_unit_topological_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['topological_average']},
        ),
    ]
