# Generated by Django 3.0.4 on 2020-06-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0005_remove_curriculum_units'),
        ('units', '0010_unit_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='curricula.Curriculum'),
            preserve_default=False,
        ),
    ]
