# Generated by Django 3.0.4 on 2020-06-14 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_auto_20200614_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='prerequisite_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
    ]
