# Generated by Django 3.0.4 on 2020-03-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200328_0905'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbugreport',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='questions.Question'),
            preserve_default=False,
        ),
    ]
