# Generated by Django 3.0.4 on 2020-03-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_questionbugreport_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbugreport',
            name='reason',
            field=models.CharField(choices=[('PI', 'There is something wrong with the question prompt.'), ('AI', 'There is something wrong with the answer(s)'), ('DI', 'The question is not displaying correctly'), ('OT', 'Other')], max_length=2),
        ),
    ]
