# Generated by Django 3.0.4 on 2020-03-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200329_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbugreport',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionbugreport',
            name='reporting_user',
        ),
        migrations.DeleteModel(
            name='GeneralBugReport',
        ),
        migrations.DeleteModel(
            name='QuestionBugReport',
        ),
    ]
