# Generated by Django 3.0.4 on 2020-03-29 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_auto_20200328_0905'),
        ('pages', '0004_auto_20200329_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_message', models.TextField(max_length=2000)),
                ('reporting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBugReport',
            fields=[
                ('generalbugreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.GeneralBugReport')),
                ('reason', models.CharField(choices=[('PI', 'There is something wrong with the question prompt.'), ('AI', 'There is something wrong with the answer(s)'), ('DI', 'The question is not displaying correctly'), ('OT', 'Other')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='questions.Question')),
            ],
            bases=('pages.generalbugreport',),
        ),
    ]
