# Generated by Django 3.0.4 on 2020-04-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lessonimage'),
        ('units', '0004_auto_20200426_1558'),
        ('pages', '0005_generalbugreport_questionbugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbugreport',
            name='reason',
            field=models.CharField(choices=[('PI', 'There is something wrong with the question prompt'), ('AI', 'There is something wrong with the answer(s)'), ('DI', 'The question is not displaying correctly'), ('OT', 'Other')], max_length=2),
        ),
        migrations.CreateModel(
            name='UnitBugReport',
            fields=[
                ('generalbugreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.GeneralBugReport')),
                ('reason', models.CharField(choices=[('DI', 'The unit is not displaying correctly'), ('OT', 'Other')], max_length=2)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='units.Unit')),
            ],
            bases=('pages.generalbugreport',),
        ),
        migrations.CreateModel(
            name='LessonBugReport',
            fields=[
                ('generalbugreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.GeneralBugReport')),
                ('reason', models.CharField(choices=[('FI', 'There is something factually incorrect with the lesson'), ('TI', 'There is are typos present in the lesson'), ('DI', 'The lesson is not displaying correctly'), ('OT', 'Other')], max_length=2)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='lessons.Lesson')),
            ],
            bases=('pages.generalbugreport',),
        ),
    ]
