# Generated by Django 3.0.4 on 2020-04-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_subject'),
        ('pages', '0006_auto_20200426_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbugreport',
            name='reason',
            field=models.CharField(choices=[('FI', 'There is something factually incorrect with the lesson'), ('TI', 'There are typos present in the lesson'), ('DI', 'The lesson is not displaying correctly'), ('OT', 'Other')], max_length=2),
        ),
        migrations.CreateModel(
            name='CurriculumBugReport',
            fields=[
                ('generalbugreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.GeneralBugReport')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='curricula.Curriculum')),
            ],
            bases=('pages.generalbugreport',),
        ),
    ]
