# Generated by Django 3.0.4 on 2020-03-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_userprofile_currently_studying'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='skillfulness',
            order_with_respect_to='skill',
        ),
    ]
