# Generated by Django 3.0.4 on 2020-04-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20200324_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='currently_studying',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='test_date',
        ),
    ]
