# Generated by Django 3.0.4 on 2020-04-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_curriculum_subject'),
        ('userprofiles', '0004_auto_20200420_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyStudying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currently_studying_through', to='curricula.Curriculum')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currently_studying_through', to='userprofiles.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currently_studying',
            field=models.ManyToManyField(through='userprofiles.CurrentlyStudying', to='curricula.Curriculum'),
        ),
    ]
