# Generated by Django 3.0.4 on 2020-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20200420_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlystudying',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
