# Generated by Django 3.0.4 on 2020-05-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0008_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_lesson_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
