# Generated by Django 3.0.4 on 2020-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0009_auto_20200514_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qotd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
