# Generated by Django 3.0.4 on 2020-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_userprofile_qotd'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillfulness',
            name='readiness',
            field=models.BooleanField(default=False),
        ),
    ]
