# Generated by Django 3.0.4 on 2020-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0011_skillfulness_readiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillfulness',
            name='readiness',
        ),
    ]
