# Generated by Django 3.0.4 on 2020-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='mathematics', unique=True),
        ),
    ]
