# Generated by Django 3.0.4 on 2020-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20200409_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='dependencies',
        ),
    ]
