# Generated by Django 3.0.4 on 2020-03-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_area', models.CharField(choices=[('MATH', 'Mathematics'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('BIOL', 'Biology')], default='MATH', max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('topological_order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['topological_order'],
            },
        ),
        migrations.CreateModel(
            name='SkillEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_skills', to='skills.Skill')),
                ('parent_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_skills', to='skills.Skill')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='related_skills',
            field=models.ManyToManyField(related_name='related_to', through='skills.SkillEdge', to='skills.Skill'),
        ),
    ]
