# Generated by Django 3.0.4 on 2020-03-24 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('skills', '0002_skill_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='subject_area',
        ),
        migrations.AlterField(
            model_name='skill',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='subjects.Subject'),
        ),
    ]
