# Generated by Django 3.0.4 on 2020-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20200324_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilledge',
            name='same_subject',
            field=models.BooleanField(default=True),
        ),
    ]
