# Generated by Django 3.0.4 on 2020-03-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('lesson_text', models.FileField(upload_to='lessons')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='skills.Skill')),
            ],
            options={
                'order_with_respect_to': 'skill',
            },
        ),
    ]
