# Generated by Django 3.0.4 on 2020-03-27 08:14

from django.db import migrations, models
import django.db.models.deletion
import lessons.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lessons.models.lesson_image_directory_path)),
                ('caption', models.CharField(blank=True, max_length=128, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lessons.Lesson')),
            ],
        ),
    ]
